services:
 dbarchive:
    container_name: percona
    image: "percona/percona-server:8.0"
    environment:
      ENVIRONMENT: "local"
      MYSQL_ROOT_PASSWORD: "password"
    networks:
       bhnoc:
         aliases:
          - "percona.bhnoc.org"
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
networks:
  bhnoc:
    external: true
    name: bhnoc
    driver: bridge
